### ISSUE TITLE
Instance of Chance object is redundant

### ISSUE THREAD

**Issue by amanpalariya** [r-unruh/chance#1]
Hi 👋

I think the function in the `Chance` class should be static so that they can be called without creating an instance of `Chance` object.

So, 👇
```dart
final chance = Chance();
print(chance.integer(min: 1, max: 10));
```
reduces to 👇
```dart
print(Chance.integer(min:1, max: 10));
```

What do you think? 😀

**Comment by r-unruh** [comment]
Practicality-wise, I think you're absolutely right.

When I made this library I was trying to immitate chance.js because I was used to the way it was (and I thought other people coming from JS would be, too). But apart from that it doesn't seem to make much sense to keep it the way it is.

I'll probably change it to the way you proposed soon, thanks!

**Comment by amanpalariya** [comment]
@blausoft Thanks for considering it.

I would like to contribute to this project. If you do not mind, could you please assign this issue to me?

**Comment by r-unruh** [comment]
Sure, let's try it out!

**Comment by r-unruh** [comment]
#2 Well done, thanks!
